{"ID9700","Anauroch Castle - outer courtyard (TotL start area)"},
{"ID9701","Anauroch Castle - south Tower basement - battle test"},
{"ID9702","Anauroch Castle - south tower upstairs - wyverns"},
{"ID9703","Anauroch Castle - west Tower basement - intelligence test"},
{"ID9704","Anauroch Castle - west Tower upstairs - Harald"},
{"ID9705","Anauroch Castle - north Tower basement - courage test"},
{"ID9706","Anauroch Castle - north Tower upstairs - harpy queen"},
{"ID9707","Anauroch Castle - east Tower basement - perseverance test"},
{"ID9708","Anauroch Castle - east Tower upstairs - Banites"},
{"ID9709","Anauroch Castle - western battlements"},
{"ID9710","Anauroch Castle - eastern battlements"},
{"ID9711","Anauroch Castle - inner courtyard"},
{"ID9712","Anauroch Castle - upper story"},
{"ID9713","Anauroch Castle - Ruined Temple of Helm"},
{"ID9714","Anauroch Castle - Watchknight Tomb"},
{"ID9715","Anauroch Castle - hideout of Hobart"},
{"ID9716","Anauroch Castle - dungeon level 1"},
{"ID9717","Anauroch Castle - dungeon level 2"},
{"ID9718","Anauroch Castle - dungeon level 3"},
{"ID9800","Anauroch Castle - Jackal Clan caverns - level 1"},
{"ID9801","Anauroch Castle - Jackal Clan caverns - level 2"},
