IF
  Global("ID9708_HIDDEN_DOOR_STATE","GLOBAL",0)
  OpenState(Myself,TRUE)
THEN
  RESPONSE #100
    SetGlobal("ID9708_HIDDEN_DOOR_STATE","GLOBAL",1)
    DisplayStringNoNameHead(LastTrigger,@91114)
END

IF
  !Global("ID9708_HIDDEN_DOOR_STATE","GLOBAL",0)
  OpenState(Myself,FALSE)
THEN
  RESPONSE #100
    SetGlobal("ID9708_HIDDEN_DOOR_STATE","GLOBAL",0)
    DisplayStringNoNameHead(LastTrigger,@91115)
END

