IF
  Global("ID9706_HIDDEN_DOOR_STATE","GLOBAL",0)
  OpenState(Myself,TRUE)
THEN
  RESPONSE #100
    SetGlobal("ID9706_HIDDEN_DOOR_STATE","GLOBAL",1)
    DisplayStringNoNameHead(LastTrigger,@91112)
END

IF
  !Global("ID9706_HIDDEN_DOOR_STATE","GLOBAL",0)
  OpenState(Myself,FALSE)
THEN
  RESPONSE #100
    SetGlobal("ID9706_HIDDEN_DOOR_STATE","GLOBAL",0)
    DisplayStringNoNameHead(LastTrigger,@91113)
END

