IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)
    FaceObject(NearestEnemyOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player2)
    FaceObject(NearestEnemyOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player3)
    FaceObject(NearestEnemyOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player4)
    FaceObject(NearestEnemyOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player5)
    FaceObject(NearestEnemyOf(Myself))
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player6)
    FaceObject(NearestEnemyOf(Myself))
END

IF
  OnCreation()
THEN
  RESPONSE #100
    NoAction()
    Continue()
END

