IF
  OR(2)
    !Global("ID#EAST_BLOCK","GLOBAL",0)
    !Global("ID#WEST_BLOCK","GLOBAL",0)
THEN
  RESPONSE #100
    Deactivate(Myself)
END

IF
  Entered([PC])
  Global("ID#EAST_BLOCK","GLOBAL",0)
  Global("ID#WEST_BLOCK","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("ID#WEST_BLOCK","GLOBAL",1)
    SetGlobal("ID#EAST_BLOCK","GLOBAL",1)
    StartCutScene("DUTRAPC")
    DisplayString(Myself,14381)
END
