IF
  See([PC])
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  Global("MAP_GROUP_HOSTILE7","MYAREA",0)
  Detect([PC])
THEN
  RESPONSE #100
    FaceObject(NearestEnemyOf(Myself))
    DisplayStringHead(Myself,@24945)
    SetGlobal("MAP_GROUP_HOSTILE7","MYAREA",1)
    Wait(2)
    Continue()
END

