IF
  Global("ID9702_HIDDEN_DOOR_STATE","GLOBAL",0)
  OpenState(Myself,TRUE)
THEN
  RESPONSE #100
    SetGlobal("ID9702_HIDDEN_DOOR_STATE","GLOBAL",1)
    DisplayStringNoNameHead(LastTrigger,@91116)
END

IF
  !Global("ID9702_HIDDEN_DOOR_STATE","GLOBAL",0)
  OpenState(Myself,FALSE)
THEN
  RESPONSE #100
    SetGlobal("ID9702_HIDDEN_DOOR_STATE","GLOBAL",0)
    DisplayStringNoNameHead(LastTrigger,@91117)
END

