IF
  Global("ID9704_HIDDEN_DOOR_STATE","GLOBAL",0)
  OpenState(Myself,TRUE)
THEN
  RESPONSE #100
    SetGlobal("ID9704_HIDDEN_DOOR_STATE","GLOBAL",1)
    DisplayStringNoNameHead(LastTrigger,@40717)
END

IF
  !Global("ID9704_HIDDEN_DOOR_STATE","GLOBAL",0)
  OpenState(Myself,FALSE)
THEN
  RESPONSE #100
    SetGlobal("ID9704_HIDDEN_DOOR_STATE","GLOBAL",0)
    DisplayStringNoNameHead(LastTrigger,@40718)
END

